export { CouponStoragePage } from './CouponStoragePage'
export { ChallengePage } from './ChallengePage'
export { ProfileEditPage } from './ProfileEditPage'
export { BobCheckHistoryPage } from './BobCheckHistoryPage'
export { FriendProfilePage } from './FriendProfilePage'
