name: Push client to personal fork for Vercel deploy

on:
    push:
        branches: ['main']
    workflow_dispatch:

jobs:
    push-to-fork:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Validate source directory
              run: |
                  echo "PWD=$(pwd)"
                  ls -la
                  test -d BabMukDang-Client || (echo "Missing source dir: BabMukDang-Client" && exit 1)
                  ls -la BabMukDang-Client

            - name: Push BabMukDang-Client to destination repo
              uses: cpina/github-action-push-to-another-repository@main
              env:
                  API_TOKEN_GITHUB: ${{ secrets.PUSH_TOKEN }}
              with:
                  source-directory: 'BabMukDang-Client'
                  destination-github-username: ${{ secrets.DEST_GH_USERNAME }}
                  destination-repository-name: ${{ secrets.DEST_REPO_NAME }}
                  user-email: ${{ secrets.DEST_EMAIL }}
                  commit-message: ${{ github.event.head_commit.message || format('Sync from {0}@{1}', github.repository, github.sha) }}
                  target-branch: main
                  create-target-branch-if-needed: true
